Repository AY2324S2-CS2103T-W10-3/tp, pull requests merged in 2024-04, with the labels that each got.

#89 Add undo command
  data/addressbook.json
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ChangeDataSourceCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.function

#90 Add functionality to allow naming of export files
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/storage/Export.java
  src/main/java/seedu/address/storage/ExportManager.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/storage/ExportManagerTest.java
Labels: type.function, type.field

#91 Add vetting functionality for csvs before importing
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/MigrateCommand.java
  src/main/java/seedu/address/storage/Import.java
  src/main/java/seedu/address/storage/ImportManager.java
  src/test/java/seedu/address/storage/ImportManagerTest.java
Labels: type.function

#93 Remove duplicate test code in import and migrate
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/MigrateCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MigrateCommandParserTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.function, type.field

#95 Find by class
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/FormClassMatchesPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/FormClassMatchesPredicateTest.java
Labels: type.function

#97 Update hyperlink for help
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#100 Update user guide for v1.3
  docs/UserGuide.md
  docs/images/AddCommandAftermath.png
  docs/images/AddCommandBox.png
  docs/images/ClearCommandAftermath.png
  docs/images/ClearCommandBox.png
  docs/images/ContactCard.png
  docs/images/DarkTheme.png
  docs/images/DeleteCommandAftermath.png
  docs/images/DeleteCommandBox.png
  docs/images/DeleteTagCommandAftermath.png
  docs/images/DeleteTagCommandBefore.png
  docs/images/DeleteTagCommandBox.png
  docs/images/EditCommandAftermath.png
  docs/images/EditCommandBox.png
  docs/images/ExitCommandBox.png
  docs/images/ExportCommandAftermath.png
  docs/images/ExportCommandAftermathCsv.png
  docs/images/ExportCommandAftermathFiles.png
  docs/images/ExportCommandBefore.png
  docs/images/ExportCommandBox.png
  docs/images/FindCommandAftermath.png
  docs/images/FindCommandBox.png
  docs/images/HelpCommandAftermath.png
  docs/images/HelpCommandBox.png
  docs/images/ImportCommandAftermath.png
  docs/images/ImportCommandBefore.png
  docs/images/ImportCommandBox.png
  docs/images/LightTheme.png
  docs/images/ListCommandAftermath.png
  docs/images/ListCommandBox.png
  docs/images/MigrateCommandAftermath.png
  docs/images/MigrateCommandBefore.png
  docs/images/MigrateCommandBeforePp.png
  docs/images/MigrateCommandBox.png
  docs/images/SortCommandAftermath.png
  docs/images/SortCommandBox.png
  docs/images/ThemeCommandBox.png
  docs/images/UiGuide.png
  docs/images/UndoCommandAftermath.png
  docs/images/UndoCommandBefore.png
  docs/images/UndoCommandBox.png
Labels: type.Document

#102 Add cd command in UG
  docs/UserGuide.md
  docs/images/CdCommandAftermath.png
  docs/images/CdCommandBefore.png
  docs/images/CdCommandBox.png
Labels: type.Document

#101 Fix styling of user guide
  docs/UserGuide.md
Labels: type.Document

#103 Clean up UG, update missing functions in tables
  docs/UserGuide.md
Labels: documentation

#137 Add known issue of leading zeroes and corresponding remedies
  docs/UserGuide.md
Labels: documentation

#141 Fix codecov not checking code coverage
  .github/workflows/gradle.yml
Labels: bug

#138 Fix some bugs in DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SearchSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SearchSequenceDiagram.png
Labels: documentation

#140 Update portfolio
  docs/team/j-wang-csma.md
Labels: type.Document

#142 Update Zhi Li's PPP
  docs/team/ongzhili.md
Labels: documentation

#143 Format addcommand sample usage, add clarifications to fields
  docs/UserGuide.md
Labels: documentation

#144 Update DG on CD command and Undo command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ChangeDataSourceSequenceDiagram.png
  docs/images/DeleteTagSequenceDiagram.png
  docs/team/wallacexuhanxiao.md
Labels: documentation

#145 Add assertions
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
Labels: type.field

#146 Add page breaks in UG for better readability
  docs/UserGuide.md
Labels: type.Document

#149 Update DG for v1.4
  docs/DeveloperGuide.md
  docs/UserGuideLocal.md
  docs/diagrams/ExportActivityDiagram.puml
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/ImportActivityDiagram.puml
  docs/diagrams/ImportSequenceDiagram.puml
  docs/diagrams/MigrateActivityDiagram.puml
  docs/diagrams/MigrateSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ExportActivityDiagram.png
  docs/images/ExportSequenceDiagram.png
  docs/images/ImportActivityDiagram.png
  docs/images/ImportSequenceDiagram.png
  docs/images/MigrateActivityDiagram.png
  docs/images/MigrateSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MigrateCommand.java
Labels: type.Document

#150 Add edit and add implementation section to DG
  docs/DeveloperGuide.md
  docs/images/AddSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
Labels: documentation

#153 Add acknowledgements section in DG
  docs/DeveloperGuide.md
Labels: documentation, type.Document

#155 Update UG and DG to match deliverables
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/UserGuideLocal.md
Labels: documentation
